### PR TITLE
Implement !quote

### PR DESCRIPTION
**Pull request by wholesomethought**
The bot replies with a random quote (excluding commands) from chat.

### CODE REVIEW

**Comment by asottile** [comment]
I was thinking we'd have a curated database of these rather than reading from all the logs (which'll just kinda give garbage most of the time) -- probably augmenting the existing database

**Comment by wholesomethought** [comment]
Gotcha, makes sense!

**Comment by asottile** [comment]
it probably wouldn't be too difficult to adapt this PR to do that if you're interested!

**Comment by wholesomethought** [comment]
Would `!quote` pull from the `motd` table or would there be a `post` table that gets populated by you and/or chat?

**Pull request closed without merging**
